### ISSUE TITLE
[Testing on attsampler on pytorch]

### ISSUE THREAD

**Issue by AlexHu123** [wkcn/AttentionSampler#4]
Hi, when I test on the attention sampler using Pytorch, I found some bugs when it creates gird for sampling ( it has 'nan' in grid ). Would it be possible for you to fix it out? Thanks in advance!

**Comment by wkcn** [comment]
It is not the bug of AttSampler Operator. 
I have tested the AttSampler in official MXNet implementation, and got 87 accuracy on CUB_200_2011.

**Comment by AlexHu123** [comment]
Thanks for your reply, I will check it
